all: measureNetworkTraffic emit emit2

measureNetworkTraffic: MeasureNetworkTraffic.c
	gcc MeasureNetworkTraffic.c -lncurses -o MeasureNetworkTraffic

emit: emit.c
	gcc emit.c -o emit

emit2: emit2.c
	gcc emit2.c -o emit2
